# Generated by Django 4.2.1 on 2023-05-31 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('timestampAdded', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=512, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(blank=True, max_length=30, null=True)),
                ('pois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='api.pointofinterest')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('pois', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='api.pointofinterest')),
            ],
        ),
    ]
