# Generated by Django 4.1.5 on 2023-06-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
