# Generated by Django 4.1.5 on 2023-06-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='pois',
        ),
    ]
