# Generated by Django 4.2.1 on 2023-06-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='id',
        ),
        migrations.AddField(
            model_name='announcement',
            name='_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
