# Generated by Django 4.1.5 on 2023-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='categories',
            field=models.ManyToManyField(related_name='categories', to='api.category'),
        ),
    ]
