# Generated by Django 4.1.5 on 2023-06-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pointofinterest_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='api.category'),
        ),
    ]
