# Generated by Django 4.1.5 on 2023-06-04 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_alter_pointofinterest_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('temporary_search', models.BooleanField()),
                ('text', models.TextField(blank=True, max_length=512, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('kilometers', models.IntegerField()),
                ('cache_locations', models.ManyToManyField(related_name='searches', to='api.pointofinterest')),
                ('categories', models.ManyToManyField(related_name='searches', to='api.category')),
                ('keywords', models.ManyToManyField(related_name='searches', to='api.keywords')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
