# Generated by Django 4.1.5 on 2023-06-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_search_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
